apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-node-app.fullname" . }}
  labels:
{{ include "my-node-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "my-node-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
