{
 "title": "Ingress Nginx",
 "tags": [ "ingress-nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Ingress Nginx TLS expire all",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(nginx_ingress_controller_ssl_expire_time_seconds{} - time()) / 86400",
     "legendFormat": "host: {{host}}, exported_namespace: {{exported_namespace}}, secret_name: {{ secret_name }}"
    }
   ]
  },
  {
   "title": "Ingress Nginx TLS expire less than 30 days",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(nginx_ingress_controller_ssl_expire_time_seconds{} - time()) / 86400 < 30",
     "legendFormat": "host: {{host}}, exported_namespace: {{exported_namespace}}, secret_name: {{ secret_name }}"
    }
   ]
  },
  {
   "title": "Ingress Nginx TLS cert info",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "nginx_ingress_controller_ssl_certificate_info ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}