{
 "title": "My-Node-App-Dashboard",
 "tags": [ "nodejs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Data_Source", "label": "Data_Source", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container OOM events",
   "type": "timeseries",
   "description": "Container OOM events",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_oom_events_total{pod=\"$pod\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container last terminated exit code",
   "type": "timeseries",
   "description": "Container last terminated exit code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_status_last_terminated_exitcode{pod=\"$pod\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{pod=\"$pod\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory cache",
   "type": "timeseries",
   "description": "Memory cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_cache{pod=\"$pod\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage per sec",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}