name: CI/CD Parent Workflow

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true

jobs:
  build-test-scan:
    uses: ./.github/workflows/build-test-scan.yaml
    with:
      image_tag: ${{ inputs.image_tag }}

  deploy:
    needs: build-test-scan
    uses: ./.github/workflows/deploy-helm-argocd.yaml
    with:
      image_tag: ${{ inputs.image_tag }}
      chart_path: "./helm/my-node-app-chart"  # path to Helm chart in the repo
