name: Deploy Node.js app via Helm + Argo CD

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Lint Kubernetes manifests using kube-linter action
      - name: Run kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          # path to the Helm chart templates
          paths: ./helm/my-node-app-chart/templates
          # optional: fail the workflow if any issues found
          fail-on-error: true  

      - name: Update Helm chart values with new image tag
        run: |
          # Path to your Helm chart inside this repo
          CHART_DIR="./helm/my-node-app-chart"

          # Docker image tag from workflow input
          IMAGE_TAG=${{ inputs.image_tag }}

          # Update values.yaml
          sed -i "s/tag:.*/tag: ${IMAGE_TAG}/" $CHART_DIR/values.yaml

          # Commit and push changes
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $CHART_DIR/values.yaml
          git commit -m "Deploy image tag ${IMAGE_TAG}"
          git push
