apiVersion: v2
name: nodejs
description: A simple Node.js app Helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/nodedotjs.svg
