replicaCount: 1

# optional overrides
nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/githubadministrator01/my-node-app   # change this to your registry/repo
  tag: 0eaddcf3f1343bf8f145bb0678d036fd59d52231
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: true
  path: /api/hello
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /api/hello
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: my-node-app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: my-node-app-tls
      hosts:
        - my-node-app.example.com

registryCreds:
  secretName: ghcr-secret
