apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: platform-services
  sources:
    - repoURL: 'https://kubernetes.github.io/ingress-nginx'
      chart: ingress-nginx
      targetRevision: 4.13.2
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/helm/ingress-nginx/values.yaml
    - repoURL: 'https://git.example.com/org/value-files.git'  # replace with your repo 
      targetRevision: main
      ref: values    
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - PruneLast=true     # prune resources in the last step
      - CreateNamespace=true  # automatically create namespace if missing
      - ServerSideApply=true  # use server-side apply for better merging