apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: platform-services
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: loki
      targetRevision: 6.40.0
      helm:
        releaseName: loki
        valueFiles:
        - $values/helm/loki/values.yaml
    - repoURL: 'https://github.com/githubadministrator01/devops-crash-course-cicd-k8s-helm-argo-actions.git'  # replace with your repo
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"    
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - PruneLast=true     # prune resources in the last step
      - CreateNamespace=true  # automatically create namespace if missing
      - ServerSideApply=true  # use server-side apply for better merging  