apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-kube-stack
  namespace: argocd
spec:
  project: platform-services
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: kube-prometheus-stack
      targetRevision: 77.6.2
      helm:
        releaseName: prom-kube-stack
        valueFiles:
        - $values/helm/prom-kube-stack/values.yaml
    - repoURL: 'https://github.com/githubadministrator01/devops-crash-course-cicd-k8s-helm-argo-actions.git'  # replace with your repo
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"    
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - PruneLast=true     # prune resources in the last step
      - CreateNamespace=true  # automatically create namespace if missing
      - ServerSideApply=true  # use server-side apply for better merging  