name: CD Parent Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true
      chart_dir:
        description: "Path to the Helm chart in the repo"
        required: true
        default: "./helm/my-node-app-chart"

jobs:
  deploy:
    needs: build-test-scan
    uses: ./.github/workflows/deploy-helm-argocd.yaml
    with:
      image_tag: ${{ secrets.image_tag }} 
      chart_dir: "./helm/my-node-app-chart"  # path to Helm chart in the repo
    secrets:
      package_token: ${{ secrets.PACKAGE_TOKEN }}  
