name: Deploy to Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy the Helm chart
        run: |
          helm upgrade \
            ${{ github.event.repository.name }} \
            helm \
            --install \
            --create-namespace \
            --namespace ${{ github.event.repository.name }} \
            --set image.repository=ghcr.io/${{ github.repository }} \
            --set image.tag=${{ github.sha }}


